version = 1
SPDX-PackageName = "Air"
SPDX-PackageSupplier = "Phoenix R&D GmbH <hello@phnx.im>"
SPDX-PackageDownloadLocation = "https://github.com/phnx-im/air"

[[annotations]]
path = "Cargo.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "server/.sqlx/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "backend/.sqlx/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "coreclient/.sqlx/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "**.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "app/test_driver/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "app/fastlane/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "app/ios/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "app/android/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "app/macos/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "app/windows/***"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "app/.fvmrc"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "app/linux/flutter/generated*"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "**/snapshots/*.snap"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "**/snapshots/*.snap.tls"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "**/snapshots/*.snap.cbor"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "app/rust_builder/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "app/lib/core/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "app/**/*.freezed.*"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "**/*frb_generated.*"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ".sql-formatter.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "**/*.arb"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "app/stores/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Phoenix R&D GmbH <hello@phnx.im>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
